FLAGS= -g -Wall



output: main.o my_mat.o
	gcc $(FLAGS) main.o my_mat.o -o output

main.o: main.c my_mat.h
	gcc $(FLAGS) -c main.c

my_mat.o: my_mat.c my_mat.h
	gcc $(FLAGS) -c my_mat.c


.PHONY: clean

clean:
	rm -f output *.o